#!/bin/bash

workflow_startup() {
    [ ! command -v xdotool &> /dev/null ] && echo "xdotool not found." && return 1

    for i in {1..5}; do xdotool key "super+$i"; sleep 1; emacs &; sleep 1; done

    apps=("thunderbird" "chromium --app=https://mail.asu.edu" "thunar" "pavucontrol" "zoom" "lxappearance" "chromium --kiosk" "brave-browser --kiosk")
    for i in {6..8}; do xdotool key "super+$i"; sleep 1; ${apps[$i-6]} &; sleep 1; done

    xdotool key "super+9"; sleep 1; start_tmux_session
}

start_tmux_session() {
    [ ! command -v tmux &> /dev/null ] && echo "tmux not found." && return 1

    tmux new-session -d -s my_session -n 'DUMMY' 'sleep 1'
    windows=("RESEARCH" "CODE" "TEX" "TESTIN" "BTOP" "CONF" "SYS" "GIT" "TEACH")
    for win in "${windows[@]}"; do tmux new-window -t my_session -n "$win"; done
    tmux kill-window -t my_session:0; tmux attach -t my_session
}

workflow_startup
